ansible_connection: network_cli
ansible_network_os: cisco.ios.ios
ansible_command_timeout: 120
ansible_timeout: 60
ansible_port: 22
snmp_group_name: NETOPS
snmp_user: snmpadmin
snmp_auth_algo: sha
snmp_auth_key: StrongAuthKey
snmp_priv_algo: aes 256
snmp_priv_key: StrongPrivKey
snmp_view: READONLY
snmp_acl: SNMP-ACL
snmp_contact: B S Dada Kahalandar
nms_hosts:
  - 10.10.40.100
  - 10.10.40.101
logging_hosts:
  - 10.10.30.50
  - 10.10.30.51
  ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1,+diffie-hellman-group-exchange-sha1'
