#Test Working
---
- name: Deploy login banner to Cisco IOS
  hosts: Test-IOS-XE-ISRV
  gather_facts: no
  vars_files:
    - "../group_vars/tenants_test-env.yml"
  roles:
    - role: config
      vars:
        banner_file: banner.j2
        commit: true
