#Test Working
---
- name: Deploy login banner to Cisco IOS
  hosts: Test-IOS-XE-ISRV
  connection: network_cli
  ansible_network_os: cisco.ios.ios
  gather_facts: no
  
  roles:
    - role: config
      vars:
        banner_file: banner.j2
        commit: true
