#logic Working - Need to work on host filtering 
---
- name: Deploy VLANs via role to Cisco IOS
  hosts: tenants_test-env:&device_types_i86bi_linuxl2-adventerprisek9-m
  gather_facts: no

  vars_files:
    - "../host_vars/{{ inventory_hostname }}.yml"
  
  roles:
    - role: ios_common/vlan
      vars:
        template_file: vlans.j2
        commit: true
