- name: Configure SNMPv3 and logging
  ios_config:
    src: "{{ lookup('template', '../templates/snmp.j2') }}"

- name: Configure logging
  ios_config:
    src: "{{ lookup('template', '../templates/logging.j2') }}"