---
vlans:
  - id: 101
    name: 101.101.101.0/24_TEST_DATA
    state: present
  - id: 201
    name: 201.201.201.0/24_TEST_SEC
    state: present
  - id: 51
    name: 51.51.51.0/24_TEST_SEC
    state: present
  - id: 1000
    name: 10.10.240.0/24_Guest
    state: present
  - id: 2002
    name: Test
    state: absent
