---
- name: Deploy SNMPv3 config
  hosts: tenants_test-env
  gather_facts: no

  vars_files:
    - "../group_vars/all.yml"
  
  roles:
    - role: logging_snmp
      vars:
        template_file: 
          - logging.j2
          - snmp.j2
        commit: true
