---
- name: Deploy VLANs via role to Cisco IOS
  hosts: tenants_test-env
  gather_facts: no
  
  tasks:
    - name: Show vlans variable
      debug:
        var: vlans
  roles:
    - role: vlans
      vars:
        template_file: vlans.j2
        commit: true
